[project]
name = "dbcompare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "connectorx==0.3.3",
    "oracledb>=2.4.1",
    "polars>=1.12.0",
    "pyarrow>=18.0.0",
    "sqlalchemy>=2.0.36",
]
